(eval-when-compile    (require 'color-theme))
(defun my-color-theme ()
  "Color theme by 6020186, created 2016-05-24."
  (interactive)
  (color-theme-install
   '(my-color-theme
     ((background-color . "#1B1D1E")
      (background-mode . dark)
      (border-color . "black")
      (cursor-color . "#F8F8F0")
      (foreground-color . "#F8F8F2")
      (mouse-color . "black"))
     ((browse-kill-ring-current-entry-face . highlight)
      (browse-kill-ring-inserted-item-face . highlight)
      (browse-kill-ring-separator-face . bold)
      (compilation-message-face . underline)
      (ibuffer-deletion-face . error)
      (ibuffer-filter-group-name-face . font-lock-doc-face)
      (ibuffer-marked-face . warning)
      (ibuffer-title-face . font-lock-type-face)
      (list-matching-lines-buffer-name-face . underline)
      (list-matching-lines-face . match)
      (tags-tag-face . default)
      (widget-mouse-face . highlight))
     (default ((t (:stipple nil :background "#1B1D1E" :foreground "#F8F8F2" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 98 :width normal :foundry "outline" :family "Consolas"))))
     (artbollocks-face ((t (:background "White" :foreground "Purple"))))
     (artbollocks-lexical-illusions-face ((t (:background "magenta" :foreground "black"))))
     (artbollocks-passive-voice-face ((t (:background "White" :foreground "Gray"))))
     (artbollocks-weasel-words-face ((t (:background "White" :foreground "Brown"))))
     (bold ((t (:bold t :weight bold))))
     (bold-italic ((t (:italic t :bold t :slant italic :weight bold))))
     (border ((t (nil))))
     (buffer-menu-buffer ((t (:bold t :weight bold))))
     (button ((t (:underline t :foreground "cyan1"))))
     (comint-highlight-input ((t (:bold t :weight bold))))
     (comint-highlight-prompt ((t (:foreground "#66D9EF"))))
     (company-echo ((t (nil))))
     (company-echo-common ((t (:foreground "firebrick1"))))
     (company-preview ((t (:background "blue4" :foreground "wheat"))))
     (company-preview-common ((t (:background "blue4" :foreground "red"))))
     (company-preview-search ((t (:foreground "wheat" :background "blue1"))))
     (company-scrollbar-bg ((t (:foreground "black" :background "gold"))))
     (company-scrollbar-fg ((t (:background "red"))))
     (company-template-field ((t (:background "yellow" :foreground "black"))))
     (company-tooltip ((t (:background "yellow" :foreground "black"))))
     (company-tooltip-annotation ((t (:background "yellow" :foreground "red4"))))
     (company-tooltip-common ((t (:background "yellow" :foreground "red"))))
     (company-tooltip-common-selection ((t (:background "orange1" :foreground "red"))))
     (company-tooltip-mouse ((t (:foreground "#000000" :background "#C4BE89"))))
     (company-tooltip-search ((t (:background "orange1" :foreground "black"))))
     (company-tooltip-selection ((t (:foreground "black" :background "orange1"))))
     (compilation-column-number ((t (:italic t :slant italic :foreground "#E6DB74"))))
     (compilation-error ((t (:bold t :weight bold :foreground "Pink"))))
     (compilation-info ((t (:bold t :weight bold :foreground "Green1"))))
     (compilation-line-number ((t (:foreground "#66D9EF"))))
     (compilation-mode-line-exit ((t (:bold t :foreground "ForestGreen" :weight bold))))
     (compilation-mode-line-fail ((t (:bold t :foreground "Red1" :weight bold))))
     (compilation-mode-line-run ((t (:bold t :foreground "DarkOrange" :weight bold))))
     (compilation-warning ((t (:bold t :weight bold :foreground "DarkOrange"))))
     (completions-annotations ((t (:italic t :slant italic))))
     (completions-common-part ((t (:family "Consolas" :foundry "outline" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#F8F8F2" :background "#1B1D1E" :stipple nil :height 98))))
     (completions-first-difference ((t (:bold t :weight bold))))
     (css-property ((t (:foreground "#66D9EF"))))
     (css-selector ((t (:foreground "#F92672"))))
     (cursor ((t (:background "#F8F8F0"))))
     (custom-face-tag ((t (:bold t :foreground "#66D9EF" :weight bold))))
     (custom-state ((t (:foreground "#A6E22E"))))
     (diff-added ((t (:bold t :foreground "#A6E22E" :weight bold))))
     (diff-context ((t (:foreground "#F8F8F2"))))
     (diff-file-header ((t (:foreground "#66D9EF"))))
     (diff-header ((t (:background "#232526" :foreground "#F8F8F2"))))
     (diff-hunk-header ((t (:background "#232526" :foreground "#AE81FF"))))
     (diff-indicator-added ((t (:foreground "#A6E22E"))))
     (diff-indicator-removed ((t (:foreground "#F92672"))))
     (diff-removed ((t (:bold t :foreground "#F92672" :weight bold))))
     (eldoc-highlight-function-argument ((t (:bold t :weight bold))))
     (error ((t (:bold t :foreground "Pink" :weight bold))))
     (escape-glyph ((t (:foreground "#E6DB74"))))
     (file-name-shadow ((t (:foreground "grey70"))))
     (fixed-pitch ((t (:family "Monospace"))))
     (flx-highlight-face ((t (:bold t :foreground "#F92672" :underline t :weight bold))))
     (flymake-errline ((t (:bold t :weight bold :foreground "Pink"))))
     (flymake-warnline ((t (:bold t :weight bold :foreground "DarkOrange"))))
     (fringe ((t (:background "#232526"))))
     (git-gutter:added ((t (:bold t :family "Consolas" :foundry "outline" :width normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :background "#1B1D1E" :stipple nil :foreground "green" :weight bold :height 98))))
     (git-gutter:deleted ((t (:bold t :foreground "red" :weight bold))))
     (git-gutter:modified ((t (:bold t :family "Consolas" :foundry "outline" :width normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :background "#1B1D1E" :stipple nil :foreground "magenta" :weight bold :height 98))))
     (git-gutter:separator ((t (:bold t :family "Consolas" :foundry "outline" :width normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :background "#1B1D1E" :stipple nil :foreground "cyan" :weight bold :height 98))))
     (git-gutter:unchanged ((t (:background "yellow"))))
     (glyphless-char ((t (:height 0.6))))
     (haskell-constructor-face ((t (:foreground "#66D9EF"))))
     (haskell-debug-heading-face ((t (:foreground "#66D9EF"))))
     (haskell-debug-keybinding-face ((t (:bold t :foreground "#66D9EF" :weight bold))))
     (haskell-debug-muted-face ((t (:foreground "#999"))))
     (haskell-debug-newline-face ((t (:bold t :background "#f0f0f0" :weight bold))))
     (haskell-debug-trace-number-face ((t (:bold t :background "#f5f5f5" :weight bold))))
     (haskell-debug-warning-face ((t (:bold t :foreground "DarkOrange" :weight bold))))
     (haskell-error-face ((t (:underline (:style wave :color "#dc322f")))))
     (haskell-hole-face ((t (:underline (:style wave :color "#6c71c4")))))
     (haskell-interactive-face-compile-error ((t (:bold t :foreground "Pink" :weight bold))))
     (haskell-interactive-face-compile-warning ((t (:bold t :foreground "DarkOrange" :weight bold))))
     (haskell-interactive-face-garbage ((t (:foreground "#E6DB74"))))
     (haskell-interactive-face-prompt ((t (:italic t :slant italic :foreground "#F92672"))))
     (haskell-interactive-face-result ((t (:foreground "#E6DB74"))))
     (haskell-keyword-face ((t (:foreground "#66D9EF"))))
     (haskell-literate-comment-face ((t (:italic t :slant italic :foreground "#E6DB74"))))
     (haskell-operator-face ((t (:foreground "#F92672"))))
     (haskell-pragma-face ((t (:foreground "#A6E22E"))))
     (haskell-type-face ((t (:foreground "#66D9EF"))))
     (haskell-warning-face ((t (:underline (:style wave :color "#b58900")))))
     (header-line ((t (:box (:line-width 1 :color "#000000" :style released-button) :background "grey20" :foreground "grey90" :box nil))))
     (help-argument-name ((t (:italic t :slant italic))))
     (highlight ((t (:background "#C4BE89" :foreground "#000000"))))
     (hl-line ((t (:background "#293739"))))
     (hydra-face-amaranth ((t (:bold t :foreground "#E52B50" :weight bold))))
     (hydra-face-blue ((t (:bold t :foreground "#8ac6f2" :weight bold))))
     (hydra-face-pink ((t (:bold t :foreground "#FF6EB4" :weight bold))))
     (hydra-face-red ((t (:bold t :foreground "#FF0000" :weight bold))))
     (hydra-face-teal ((t (:bold t :foreground "#367588" :weight bold))))
     (icompletep-choices ((t (:foreground "#F92672"))))
     (icompletep-determined ((t (:foreground "#A6E22E"))))
     (icompletep-keys ((t (:foreground "#F92672"))))
     (icompletep-nb-candidates ((t (:foreground "#AE81FF"))))
     (ido-first-match ((t (:bold t :weight bold))))
     (ido-incomplete-regexp ((t (:foreground "#FFFFFF" :background "#333333"))))
     (ido-indicator ((t (:background "red1" :foreground "yellow1" :width condensed))))
     (ido-only-match ((t (:foreground "ForestGreen"))))
     (ido-subdir ((t (:foreground "red1"))))
     (ido-virtual ((t (:foreground "#A6E22E"))))
     (isearch ((t (:background "#000000" :foreground "#C4BE89"))))
     (isearch-fail ((t (:background "#333333" :foreground "#FFFFFF"))))
     (italic ((t (:italic t :slant italic))))
     (lazy-highlight ((t (:background "#000000" :foreground "#465457"))))
     (link ((t (:foreground "cyan1" :underline t))))
     (link-visited ((t (:underline t :foreground "violet"))))
     (lv-separator ((t (:background "grey30"))))
     (markdown-blockquote-face ((t (:italic t :slant italic))))
     (markdown-bold-face ((t (:bold t :weight bold))))
     (markdown-comment-face ((t (:foreground "#465457"))))
     (markdown-header-face ((t (:weight normal))))
     (markdown-header-face-1 ((t (:foreground "#66D9EF"))))
     (markdown-header-face-2 ((t (:foreground "#F92672"))))
     (markdown-header-face-3 ((t (:foreground "#A6E22E"))))
     (markdown-header-face-4 ((t (:foreground "#AE81FF"))))
     (markdown-header-face-5 ((t (:foreground "#E6DB74"))))
     (markdown-header-face-6 ((t (:foreground "#66D9EF"))))
     (markdown-inline-code-face ((t (:foreground "#66D9EF"))))
     (markdown-italic-face ((t (:italic t :slant italic))))
     (markdown-link-face ((t (:foreground "#66D9EF"))))
     (markdown-link-title-face ((t (:foreground "#F92672"))))
     (markdown-list-face ((t (:foreground "#A6E22E"))))
     (markdown-math-face ((t (:italic t :foreground "#AE81FF" :slant italic))))
     (markdown-pre-face ((t (:foreground "#AE81FF"))))
     (markdown-reference-face ((t (:foreground "#66D9EF"))))
     (markdown-url-face ((t (:foreground "#E6DB74"))))
     (match ((t (:background "RoyalBlue3"))))
     (menu ((t (:foreground "systemmenu" :background "systemmenutext"))))
     (minibuffer-prompt ((t (:foreground "#66D9EF"))))
     (mode-line ((t (:background "#000000" :foreground "#F8F8F2" :box (:line-width 1 :color "#000000" :style released-button)))))
     (mode-line-buffer-id ((t (:bold t :background "#000000" :weight semi-bold))))
     (mode-line-emphasis ((t (:bold t :weight bold))))
     (mode-line-highlight ((t (:box (:line-width 2 :color "grey40" :style released-button)))))
     (mode-line-inactive ((t (:background "#000000" :foreground "#BCBCBC" :box (:line-width 1 :color "#232526")))))
     (mode-line-mousable ((t (:background "#000000" :foreground "#BCBCBC"))))
     (mode-line-mousable-minor-mode ((t (:background "#000000" :foreground "#BCBCBC"))))
     (mouse ((t (nil))))
     (mumamo-background-chunk-major ((t (:background "#272822"))))
     (mumamo-background-chunk-submode ((t (:background "#1B1D1E"))))
     (next-error ((t (:background "#403D3D"))))
     (nobreak-space ((t (:foreground "#E6DB74" :underline t))))
     (outline-1 ((t (:foreground "#66D9EF"))))
     (outline-2 ((t (:foreground "#F92672"))))
     (outline-3 ((t (:foreground "#A6E22E"))))
     (outline-4 ((t (:foreground "#AE81FF"))))
     (outline-5 ((t (:foreground "#E6DB74"))))
     (outline-6 ((t (:foreground "#66D9EF"))))
     (outline-7 ((t (:foreground "#F92672"))))
     (outline-8 ((t (:foreground "#A6E22E"))))
     (page-break-lines ((t (:foreground "#465457" :slant normal :weight normal))))
     (query-replace ((t (:foreground "#C4BE89" :background "#000000"))))
     (rainbow-delimiters-depth-1-face ((t (:foreground "grey55"))))
     (rainbow-delimiters-depth-2-face ((t (:foreground "#93a8c6"))))
     (rainbow-delimiters-depth-3-face ((t (:foreground "#b0b1a3"))))
     (rainbow-delimiters-depth-4-face ((t (:foreground "#97b098"))))
     (rainbow-delimiters-depth-5-face ((t (:foreground "#aebed8"))))
     (rainbow-delimiters-depth-6-face ((t (:foreground "#b0b0b3"))))
     (rainbow-delimiters-depth-7-face ((t (:foreground "#90a890"))))
     (rainbow-delimiters-depth-8-face ((t (:foreground "#a2b6da"))))
     (rainbow-delimiters-depth-9-face ((t (:foreground "#9cb6ad"))))
     (rainbow-delimiters-mismatched-face ((t (:foreground "#88090B"))))
     (rainbow-delimiters-unmatched-face ((t (:foreground "#88090B"))))
     (region ((t (:background "#403D3D"))))
     (scroll-bar ((t (:foreground "systemscrollbar"))))
     (secondary-selection ((t (:background "#272822"))))
     (shadow ((t (:foreground "grey70"))))
     (show-paren-match-face ((t (:background "#FD971F" :foreground "#000000"))))
     (show-paren-mismatch-face ((t (:background "#1E0010" :foreground "#960050"))))
     (success ((t (:bold t :foreground "Green1" :weight bold))))
     (tool-bar ((t (:background "systembuttonface" :foreground "systembuttontext" :box (:line-width 1 :style released-button)))))
     (tooltip ((t (:family "Sans Serif" :background "systeminfowindow" :foreground "systeminfotext"))))
     (trailing-whitespace ((t (:background "red1"))))
     (underline ((t (:underline t))))
     (variable-pitch ((t (:family "Sans Serif"))))
     (vertical-border ((t (nil))))
     (w3m-haddock-heading-face ((t (:foreground "#000000" :background "#C4BE89"))))
     (warning ((t (:bold t :foreground "DarkOrange" :weight bold))))
     (which-func ((t (:foreground "Blue1"))))
     (which-key-command-description-face ((t (:italic t :slant italic :foreground "#F92672"))))
     (which-key-group-description-face ((t (:foreground "#66D9EF"))))
     (which-key-highlighted-command-face ((t (:italic t :foreground "#F92672" :slant italic :underline t))))
     (which-key-key-face ((t (:foreground "#AE81FF"))))
     (which-key-local-map-description-face ((t (:italic t :foreground "#F92672" :slant italic))))
     (which-key-note-face ((t (:italic t :foreground "#465457" :slant italic))))
     (which-key-separator-face ((t (:italic t :slant italic :foreground "#465457"))))
     (which-key-special-key-face ((t (:bold t :background "#AE81FF" :weight bold))))
     (widget-button ((t (:bold t :weight bold))))
     (widget-button-pressed ((t (:foreground "red1"))))
     (widget-documentation ((t (:foreground "lime green"))))
     (widget-field ((t (:background "dim gray"))))
     (widget-inactive ((t (:background "#ff0000"))))
     (widget-single-line-field ((t (:background "dim gray"))))
     (window-numbering-face ((t (:bold t :foreground "DeepPink" :underline "DeepPink" :weight bold))))
     (woman-addition ((t (:foreground "#AE81FF"))))
     (woman-bold ((t (:foreground "#F92672"))))
     (woman-italic ((t (:foreground "#A6E22E"))))
     (woman-unknown ((t (:foreground "#66D9EF")))))))
(add-to-list 'color-themes '(my-color-theme  "murphytalk" "Mu Lu"))
